version: '2.0'

services:

  users-service:
    container_name: users-service
    build: .
    volumes:
      - '.:/user/src/app'
    ports:
      - 5001:500 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
